### ISSUE TITLE
Hubboard displays as 'ruby' on the dock

### ISSUE THREAD

**Issue by veryhappythings** [lukaszkorecki/Hubboard#4]
It'd be lovely if it had a little octocat icon or something too!

**Comment by lukaszkorecki** [comment]
That would require renaming the interpreter binary (or doing some symlink magic).

I'll see what can be done about this.

**Comment by lukaszkorecki** [comment]
Closed by faf8b4e856493321afd130ff7448b7eff5229c5a + changes to rake osx:package task (app icon is now being set)
